### ISSUE TITLE
Ruby/YARD support 

### ISSUE THREAD

**Issue by eirvandelden** [maxgrafik/DocBlockr.novaextension#14]
Hi!

Super cool to see that you've ported another extension to Nova :)

If I look at the documentation, the format is not very different from the one used by [YARD](https://yardoc.org/features.html).

The entire Documentation API can be found here: https://rubydoc.info/gems/yard

Would it be possible to add YARD support to DocBlockr? 😄

**Comment by maxgrafik** [comment]
I think I can add at least some basic support. Although there seems to be a variety of commenting styles for ruby. May take some time 😉

**Comment by eirvandelden** [comment]
If you add some basic support I'll try to help and expand on it 😄 
JS isn't my cup of tea, but it's doable with a base to work with.

We're expecting a baby, so take your time. I'm glad you're willing to do this 👍🏼

**Comment by maxgrafik** [comment]
Hey, I hope all is well. I just updated the [develop branch](https://github.com/maxgrafik/DocBlockr.novaextension/tree/develop) with added ruby support. You may want to check it out.

**Comment by eirvandelden** [comment]
Awesome, thanks! I'll check out the develop branch and try it out locally ❤️

**Comment by eirvandelden** [comment]
Wow, you implemented both RDoc AND YarDoc, thanks!

It works perfectly, thanks a bunch!
