### ISSUE TITLE
Support for JSX files?

### ISSUE THREAD

**Issue by mattjis** [maxgrafik/DocBlockr.novaextension#6]
I'd love if the extension supported JSX syntax files :)

**Comment by maxgrafik** [comment]
Sorry this took so long. I just published a new version which adds basic support for JSX/TSX. Enabling JavaScript in the settings also enables it for JSX. Same for TypeScript/TSX.
However, I have no experience with React at all so I expect some things to be broken. Feel free to report any issues.
