### ISSUE TITLE
Extension appears broken in Nova 8.1

### ISSUE THREAD

**Issue by lolbat** [maxgrafik/DocBlockr.novaextension#9]
I updated to Nova 8.1 yesterday and since then DocBlockr appears to not be working.

Regardless of the file I am in when I activate DocBlokr using an in-file action all I get is ` /**` inserted plus a line break.

**Comment by maxgrafik** [comment]
I just updated to 8.1 and found no issues. Did you change any settings in Nova? Or install new extensions?

**Comment by lolbat** [comment]
I am running 8.2 now and the issue has been resolved. I am not sure what it was but it only appears to have been affecting DocBlockr. Mind you, DocBlockr is the only extension I have that inserts text into a document so it could have been a more general issue.
